import dotenv from 'dotenv';
dotenv.config();
export const PORT=process.env.PORT;
export const DB_NAME=process.env.DB_NAME;
export const DB_USER=process.env.DB_USER;
export const DB_PASSWORD=process.env.DB_PASSWORD;
export const HOST=process.env.HOST;
export const DILECT=process.env.DILECT;
export const SECERATE_KEY=process.env.SECERATE_KEY;
export const GMAIL_APP_PASS=process.env.GMAIL_APP_PASS;
export const GMAIL=process.env.GMAIL;
export const CLOUDINARY_NAME=process.env.CLOUDINARY_NAME;
export const CLOUDINARY_API_KEY=process.env.CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET=process.env.CLOUDINARY_API_SECRET;
