import express from 'express';
import { isAuthenticated } from '../auth/isAuthenticated.js';
import { roleAccessMiddleWare } from '../../middleware/roleAccessMiddleware.js';
import { addProduct, getAllProduct, getProductById } from './product.controller.js';
import { upload } from '../../middleware/upload.js';
const router=express.Router();
router.post("/",upload.array("images",5), isAuthenticated,roleAccessMiddleWare('ADMIN','SELLER'),addProduct);
router.get("/",getAllProduct);
router.get("/:id",getProductById);
export default router;